Make ready for Django 2.1
justinmayer/django-elevate pull request #6
Opened 2019-01-28 17:10 UTC by gabn88

is_safe_url public API changed

2019-01-28 17:21 UTC, justinmayer commented
Thank you for the submission, @gabn88. Did you run the tests locally? As you can see here in the PR, it seems Travis is reporting that the tests are not passing, presumably because you did not include backwards-compatibile logic for previous versions of Django:
```
TypeError: is_safe_url() got an unexpected keyword argument 'allowed_hosts'
```
Given that we currently support Django versions going back to 1.8, would you please consider updating this pull request to support the previous syntax and ensure all tests pass on Django versions 1.8 through 2.0 as well?

2019-01-28 18:25 UTC, gabn88 commented
It should be good to go now, the failing test is a flake test in a tests.py file I did not touch.

2019-01-28 18:59 UTC, justinmayer commented
That Flake8 error is odd — I don't see that when running it on my workstation on current master.

@moggers87: Flake8 issues aside, do you have any thoughts on the implementation here?

2019-01-28 21:10 UTC, moggers87 submitted a review, later dismissed
Also Django 2.1 needs to be added to `tox.ini` so it actually gets tested. There may be other breakages that we're not aware of.

2019-01-28 21:10 UTC, moggers87 commented on elevate/views.py
> +
This same chunk of code is repeated twice, I think it would be better to wrap this in our own function. Maybe even a unit test would be in order too.

2019-01-28 21:12 UTC, moggers87 commented
Oh, and the flake8 error can be ignored. IIRC, flake8 now checks for invalid escape codes which some future version of Python will throw an error at.

2019-01-29 14:29 UTC, gabn88 commented on elevate/views.py
> +
It was just a dict replace, but I have made it a seperate function, or do you mean to wrap the whole is_safe_url function?

2019-01-29 15:15 UTC, moggers87 commented on elevate/views.py
> +
I meant wrapping `is_safe_url`.

Also, could you change the version check to be for 1.11 and above? Django 1.11 will issue a warning if you use the `host` kwarg.

2019-01-29 15:17 UTC, moggers87 commented on tox.ini
> +    django20: Django>=2.0,<2.2
This is wrong, we need to test both Django 2.0 as well as 2.1. I.e.:

```
django20: Django>=2.0,<2.1
django21: Dango>=2.1,<2.2
```

Also make sure to update the envlist with `django21`

2019-01-29 15:57 UTC, gabn88 commented
Not sure why the tests are failing now. I only see the python 3.7 version is failing because I can't be found apparently... Maybe you can help me with the last bit? I believe the code is now correct.

2019-01-29 16:27 UTC, moggers87 commented
You can ignore 3.7 for now, I'll open a separate issue for that.

2019-01-29 16:32 UTC, moggers87 commented on elevate/compat.py
> +    return is_safe_url(url=url, host=allowed_hosts)
You're redefining `is_safe_url` with this function, try using `from django.utils import http` and then calling `http.is_safe_url` to avoid this.

2019-01-30 07:28 UTC, gabn88 reviewed
done

2019-01-30 07:28 UTC, gabn88 commented on tox.ini
> +    django20: Django>=2.0,<2.2
Changed!

2019-01-30 07:28 UTC, gabn88 commented on elevate/compat.py
> +    return is_safe_url(url=url, host=allowed_hosts)
You are completely right that this is very sloppy from me, I guess I'm not having my best day today. I fixed it.

2019-01-30 07:29 UTC, gabn88 reviewed
done

2019-01-30 12:13 UTC, moggers87 requested changes
Code-wise this is ready for merging, you just need to remove Python 3.7 (it's is off-topic for this PR in my opinion) and restore Django 2.0 testing in tox.ini

Edit: assuming those test failures fix themselves when you sort out the issues I pointed out in tox.ini - check travis ci to see what's actually up with that.

2019-01-30 12:13 UTC, moggers87 commented on .travis.yml
> +      sudo: true
Python 3.7 support should be added separately, so you can remove this.

2019-01-30 12:13 UTC, moggers87 commented on tox.ini
> +    django20: Django>=2.0,<2.2
This doesn't appear to have changed on github, did you push your changes?

2019-01-30 12:13 UTC, moggers87 commented on tox.ini
> +    {py36,py37}-django{111,21}
Python 3.7 support should be added separately, so you can remove this.

2019-01-30 12:13 UTC, moggers87 commented on tox.ini
> +    3.7: py37
Python 3.7 support should be added separately, so you can remove this.

2019-01-30 12:13 UTC, moggers87 commented on tox.ini
> +    {py36,py37}-django{111,21}
Also, you've removed Django 2.0 from the tests again.

2019-03-07 16:38 UTC, moggers87 commented
@gabn88 are you still working on this?

2019-03-07 16:40 UTC, gabn88 commented
To be honoust I’m not working on it anymore, if someone else could finish it that would be great.

2019-03-07 16:42 UTC, moggers87 commented
OK, thanks for the update. I'll close this PR so you don't get notification spam on future work.

2019-03-07 16:42 UTC, closed without merging